export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL";

export const CONTACT_CREATE_REQUEST = "CONTACT_CREATE_REQUEST";
export const CONTACT_CREATE_SUCCESS = "CONTACT_CREATE_SUCCESS";
export const CONTACT_CREATE_FAIL = "CONTACT_CREATE_FAIL";

export const CONTACT_UPDATE_REQUEST = "CONTACT_UPDATE_REQUEST";
export const CONTACT_UPDATE_SUCCESS = "CONTACT_UPDATE_SUCCESS";
export const CONTACT_UPDATE_FAIL = "CONTACT_UPDATE_FAIL";

export const CONTACT_DELETE_REQUEST = "CONTACT_DELETE_REQUEST";
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS";
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL";

export const CONTACT_UPDATEONE_REQUEST = "CONTACT_UPDATEONE_REQUEST";
export const CONTACT_UPDATEONE_SUCCESS = "CONTACT_UPDATEONE_SUCCESS";
export const CONTACT_UPDATEONE_FAIL = "CONTACT_UPDATEONE_FAIL";

export const CONTACT_DELETEONE_REQUEST = "CONTACT_DELETEONE_REQUEST";
export const CONTACT_DELETEONE_SUCCESS = "CONTACT_DELETEONE_SUCCESS";
export const CONTACT_DELETEONE_FAIL = "CONTACT_DELETEONE_FAIL";
